### ISSUE TITLE
Debug log when connecting to Slack (https://slack.com) IRC gateway

### ISSUE THREAD

**Issue by ksexton** [jorgenschaefer/circe#164] opened 2015-05-18 21:32 UTC
```
E: "conn.connected" 
C: PASS redacted
C: NICK user
C: USER username 8 * :User Name
S: :slackbot PRIVMSG user :VERSION
E: "PRIVMSG" "slackbot" "user" "VERSION"
E: "irc.ctcp" "slackbot" "user" "VERSION" nil
E: "irc.ctcp.VERSION" "slackbot" "user" nil
C: NOTICE slackbot :VERSION Circe: Client for IRC in Emacs, version 1.6
S: :irc.tinyspeck.com 004 irc.tinyspeck.com IRC-SLACK gateway
E: "004" "irc.tinyspeck.com" "irc.tinyspeck.com" "IRC-SLACK" "gateway"
S: :irc.tinyspeck.com 001 user Welcome to Slack IRC Gateway server
E: "001" "irc.tinyspeck.com" "user" "Welcome" "to" "Slack" "IRC" "Gateway" "server"
S: :irc.tinyspeck.com 005 user MAP SILENCE=15 WHOX WALLCHOPS WALLVOICES USERIP CPRIVMSG CNOTICE MODES=6 MAXCHANNELS=100 SAFELIST :are supported by this server
E: "005" "irc.tinyspeck.com" "user" "MAP" "SILENCE=15" "WHOX" "WALLCHOPS" "WALLVOICES" "USERIP" "CPRIVMSG" "CNOTICE" "MODES=6" "MAXCHANNELS=100" "SAFELIST" "are supported by this server"
S: :irc.tinyspeck.com 005 user NICKLEN=32 TOPICLEN=160 AWAYLEN=160 CHANTYPES=# PREFIX=(ov)@+ CHANMODES=b,k,l,rimnpst CASEMAPPING=rfc1459 :are supported by this server
E: "005" "irc.tinyspeck.com" "user" "NICKLEN=32" "TOPICLEN=160" "AWAYLEN=160" "CHANTYPES=#" "PREFIX=(ov)@+" "CHANMODES=b,k,l,rimnpst" "CASEMAPPING=rfc1459" "are supported by this server"
S: :irc.tinyspeck.com 251 user :there are 22 users 
E: "251" "irc.tinyspeck.com" "user" "there are 22 users "
S: :irc.tinyspeck.com 375 : Message of the day
E: "375" "irc.tinyspeck.com" " Message of the day"
S: :irc.tinyspeck.com 372 : WELCOME TO SLACK...
E: "372" "irc.tinyspeck.com" " WELCOME TO SLACK..."
S: :irc.tinyspeck.com 376 : End of MOTD command
E: "376" "irc.tinyspeck.com" " End of MOTD command"
S: :user!user@irc.tinyspeck.com JOIN #channel-name
E: "JOIN" "user!user@irc.tinyspeck.com" "#channel-name"
S: :irc.tinyspeck.com 332 user #channel-name :A place for non-work banter, links, articles of interest, humor or anything else which you'd like concentrated in some place other than work-related channels.
E: "332" "irc.tinyspeck.com" "user" "#channel-name" "A place for non-work banter, links, articles of interest, humor or anything else which you'd like concentrated in some place other than work-related channels."
S: :irc.tinyspeck.com 353 user = #channel-name :user1 user2 user3 user 
E: "353" "irc.tinyspeck.com" "user" "=" "#channel-name" "user1 user2 user3 "
S: :irc.tinyspeck.com 366 user #channel-name :End of /NAMES list.
E: "366" "irc.tinyspeck.com" "user" "#channel-name" "End of /NAMES list."
S: :user1!user1@irc.tinyspeck.com MODE #channel-name +v user1 : active
E: "MODE" "user1!user1@irc.tinyspeck.com" "#channel-name" "+v" "user1" " active"
S: :user3!user3@irc.tinyspeck.com MODE #channel-name +v user3 : active
E: "MODE" "user3!user3@irc.tinyspeck.com" "#channel-name" "+v" "user3" " active"
S: :user!user@irc.tinyspeck.com MODE #channel-name +v user : active
E: "MODE" "user!user@irc.tinyspeck.com" "#channel-name" "+v" "user" " active"
S: :user!user@irc.tinyspeck.com MODE #channel-name +v user : active
E: "MODE" "user!user@irc.tinyspeck.com" "#channel-name" "+v" "user" " active"
```

**Comment by ksexton** [comment] 2015-05-18 21:40
Here are the errors seen in messages log:

```
Error running event "001" handler irc-handle-registration--rpl-welcome: (wrong-number-of-arguments #[(conn event sender target text) \302\303\304#\210\305\306	#\207 [conn target irc-connection-put :connection-state registered irc-event-emit irc.registered] 4] 10)
Error running event "001" handler irc-handle-state-tracking--rpl-welcome: (wrong-number-of-arguments #[(conn event sender target text) \302\303	#\207 [conn target irc-connection-put :current-nick] 4] 10)
Error running event nil handler circe-irc-legacy-bridge: (error Index for format out of range: "1") [3 times]
Error running event "353" handler irc-handle-state-tracking--rpl-namreply: (wrong-type-argument arrayp nil)
Error running event "366" handler irc-handle-state-tracking--rpl-endofnames: (wrong-type-argument arrayp nil)
Error running event "353" handler irc-handle-state-tracking--rpl-namreply: (wrong-type-argument arrayp nil)
Error running event "366" handler irc-handle-state-tracking--rpl-endofnames: (wrong-type-argument arrayp nil)
Error running event "353" handler irc-handle-state-tracking--rpl-namreply: (wrong-type-argument arrayp nil)
Error running event "366" handler irc-handle-state-tracking--rpl-endofnames: (wrong-type-argument arrayp nil)
Error running event "353" handler irc-handle-state-tracking--rpl-namreply: (wrong-type-argument arrayp nil)
Error running event "366" handler irc-handle-state-tracking--rpl-endofnames: (wrong-type-argument arrayp nil)
Error running event "353" handler irc-handle-state-tracking--rpl-namreply: (wrong-type-argument arrayp nil)
Error running event "366" handler irc-handle-state-tracking--rpl-endofnames: (wrong-type-argument arrayp nil)
```

**Comment by jorgenschaefer** [comment] 2015-05-18 21:41
Thank you for the report!

From a quick glance, at least the 001 numeric sends spurious arguments and handlers should ignore them. Not sure why RPL_NAMREPLY fails.

This will take a bit to sort out I am afraid :-)

**Comment by jorgenschaefer** [comment] 2015-05-19 08:00
> `Error running event "001" handler irc-handle-registration--rpl-welcome: (wrong-number-of-arguments #[(conn event sender target text) \302�\303\304#\210\305�\306    #\207 [conn target irc-connection-put :connection-state registered irc-event-emit irc.registered] 4] 10)`
> `Error running event "001" handler irc-handle-state-tracking--rpl-welcome: (wrong-number-of-arguments #[(conn event sender target text) \302�\303    #\207 [conn target irc-connection-put :current-nick] 4] 10)`

Slack forgets to add a colon to indicate the last argument in the RPL_WELCOME message:

`:irc.tinyspeck.com 001 user Welcome to Slack IRC Gateway server`

Circe can easily be more lenient there. You can do a quickfix locally by changing `irc-handle-registration--rpl-welcome` and `irc-handle-state-tracking--rpl-welcome` in irc.el to have a signature of `(conn event sender target &rest text)`:

```Lisp
(defun irc-handle-registration--rpl-welcome (conn event sender target
                                                  &rest text)
  (irc-connection-put conn :connection-state 'registered)
  (irc-event-emit conn "irc.registered" target))

(defun irc-handle-state-tracking--rpl-welcome (conn event sender target
                                                    &rest text)
  (irc-connection-put conn :current-nick target))
```

> Error running event nil handler circe-irc-legacy-bridge: (error Index for format out of range: "1") [3 times]

Slack forgets the target in RPL_MOTDSTART:

`:irc.tinyspeck.com 375 : Message of the day`

There should be the current user's nick after the 375 numeric. Hence, Circe's `circe-format-server-numeric` assumes that ": Message of the day" is the target nick, ignores it, and tries to access the argument after that as a body argument.

Same thing for 372 and 376.

You can fix this locally by doing

```Lisp
(circe-set-display-handler "372" nil)
(circe-set-display-handler "375" nil)
(circe-set-display-handler "376" nil)
```

> `Error running event "353" handler irc-handle-state-tracking--rpl-namreply: (wrong-type-argument arrayp nil)`
> `Error running event "366" handler irc-handle-state-tracking--rpl-endofnames: (wrong-type-argument arrayp nil)`

I can't reproduce these locally. Could you use `M-x toggle-debug-on-error` and provide the backtrace for these, after applying the fixes above?

**Comment by kostajh** [comment] 2015-07-03 01:47
So, does Circe work with Slack's IRC gateway? I can't get it working, but I'm stuck at providing a password to Slack. @ksexton do you mind sharing what your configuration looks like?

**Comment by jorgenschaefer** [comment] 2015-07-03 08:05
> So, does Circe work with Slack's IRC gateway?

A good question! The development version should be less susceptible to the broken IRC protocol Slack apparently uses, but there are a few more issues (the 372, 375 and 376 numerics above, which you can fix as described).

> I'm stuck at providing a password 

Does Slack use the normal IRC protocol PASS command? If so, you can provide it using the `:pass` keyword argument to the `circe` function or via `circe-network-options`.

**Comment by marsam** [comment] 2015-07-03 17:04
Hi:

I’ve contacted with Slack (44 days ago) about this issue and their response (7 days ago) was:

> Hi Mario,
>
> Thanks so much for your patience while we've looked into this, and I'm sorry for the delay in getting back to you. It does seem that we could be closer to protocol here with the IRC gateway. Our engineers have made a note of your feedback. They'll be working upgrading the IRC gateway in the coming months and we hope to be making some good improvements for you soon. (Specifically, I will let you know when we have any update regarding the issue you've reported here with the MOTD.)
>
> Best,
>
> Carrie S.

So there is not a soon fix from the Slack side :(.

P.S: I’ve previously contacted about #95, and the response was about the same. Basically the irc gateway is second class citizen for Slack.

**Comment by jorgenschaefer** [comment] 2015-07-04 10:16
Ok, thanks for contacting them. Circe can just try and deal with that I guess.

So weirdo stuff from Slack that Circe does not handle correctly yet:

```
:irc.tinyspeck.com 372 : WELCOME TO SLACK...
:irc.tinyspeck.com 375 : Message of the day
:irc.tinyspeck.com 376 : End of MOTD command
```

All of those forget the target of the message. The bug is that `lui-format` throws an error if it tries to access an argument that does not exist, in this case, the 2nd argument. So we can either have `lui-format` not throw an error if there are too few positional arguments, or define manual display handlers for all three messages to handle slack specifically.

I'm tending towards the former.

Does applying this patch to HEAD make Circe work with Slack?

```diff
diff --git a/lui-format.el b/lui-format.el                                      
index 7247584..68cc0ff 100644                                                   
--- a/lui-format.el                                                             
+++ b/lui-format.el                                                             
@@ -173,7 +173,7 @@ See `lui-format' for details."
                      " ")                                                      
         (or (nth (string-to-number from)                                       
                  indexed-args)                                                 
-            (error "Index for format out of range: %S" from)))))               
+            ""))))                                                             
    (t                                                                          
     (or (plist-get keywords (intern identifier))                               
         (error "Unknown keyword argument %S" identifier)))))                
```

**Comment by kostajh** [comment] 2015-07-05 00:36
@jorgenschaefer I'd love to test but I'm not able to authenticate. I'm not sure what I'm doing wrong as it shouldn't be too complicated; for ERC, for example, my settings are limited to 
``` elisp
(erc-tls :server "myorganization.irc.slack.com" :port "6667" :nick "kostajh" :password erc-password)
```
Whereas for Circe I have as an entry in `circe-network-options:`:

``` elisp
("Slack"
         :nick "kostajh"
         :channels ("#general")
         :host "myorganization.irc.slack.com"
         :user "kostajh"
         :tls t
         :port "6667"
         :nickserv-password "redacted"
         :pass "redacted")
)
 ```

And I get this error when trying to connect: `*** [444 from nil] kostajh no password!!!`

**Comment by jorgenschaefer** [comment] 2015-07-05 06:32
Try using :pass not :nickserv-password - does that work?

**Comment by jorgenschaefer** [comment] 2015-07-05 06:35
Oops, sorry, just saw that you do. Hm. Can you set `irc-debug-log` to t and
see if the `*IRC ...*` buffer contains some info abou this? (Assuming you
use the devel version of Circe)

**Comment by kostajh** [comment] 2015-07-13 16:39
@jorgenschaefer I figured it might be easier to invite you to a Slack account, just emailed you an invite to https://circe-debug.slack.com

I will try to debug myself and esnd you info

**Comment by jorgenschaefer** [comment] 2015-07-15 08:35
Thanks, I received the invite, but it will be a bit until I can work on this again.

**Comment by jorgenschaefer** [comment] 2015-07-21 16:10
With the last changes above, I can successfully connect to Slack.using this call:

```
(circe "Slack"
       :host "circe-debug.irc.slack.com"
       :nick "jorgenschaefer"
       :pass "top secret password"
       :port 6667
       :tls t)
```

Can you confirm this works for you, too?

**Comment by kostajh** [comment] 2015-07-21 16:28
It works! Thank you very much.

Jorgen Schäfer writes:

> With the last changes above, I can successfully connect to Slack.using this call:
>
> ```
> (circe "Slack"
>        :host "circe-debug.irc.slack.com"
>        :nick "jorgenschaefer"
>        :pass "top secret password"
>        :port 6667
>        :tls t)
> ```
>
> Can you confirm this works for you, too?
>
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/jorgenschaefer/circe/issues/164#issuecomment-123387439

-- 
kosta@kostaharlan.net

**Comment by jorgenschaefer** [comment] 2015-07-21 16:32
Great, closing this issue then :-) Please do not hesitate to open a new one if there are any more problems, and enjoy Circe!

**Closed by jorgenschaefer** 2015-07-21 16:32 UTC
Labels: bug, More info needed

**Comment by wlad** [comment] 2015-08-11 16:52
Hey guys. The above does not work if one has the password as the result of a call to a function that reads it from private.el

eval-region: Symbol's value as variable is void: my-cnsirc-password

**Comment by jorgenschaefer** [comment] 2015-08-11 16:59
Hello wlad, thanks for the report – can you provide a traceback using `M-x toggle-debug-on-error`?

**Comment by wlad** [comment] 2015-08-11 22:26
Sending it as a variable also fails. It seems that irc.el is not sending it as a string. Will send both tracebacks later. (PS. similar problem with freenode nickserv authentication, putting the actual password on circe-network-options works fine though)

**Comment by wasamasa** [comment] 2015-08-12 06:35
Keep in mind that a symbol of a function is expected. So, if you're really
using a variable, it must hold such a symbol as value. If it is used in a
quoted context, don't forget to unquote it, otherwise the variable name
will be interpreted as that symbol and function lookup will fail.
