### ISSUE TITLE
Add option to disable printing of Server-Messages in Queries from bitlbee Server connected via weechat proxy

### ISSUE THREAD

**Issue by V155** [jorgenschaefer/circe#178] opened 2015-06-16 09:48 UTC
When I am connected to a weechat-proxy to my bitlbee buffer and got an opened query i get periodically (perhaps when a disconnect happened due to bad wlan) the names of the users and their statuses printed inside the query buffer like they are printed in the &bitlbee channel.

**Comment by jorgenschaefer** [comment] 2015-06-16 09:50
Thanks for the report!

Could you set `irc-debug-log` to `t` and provide the contents of the `*IRC ...*` protocol buffer for when this happens?

**Comment by V155** [comment] 2015-06-16 09:51
I use the git Version "868d0928ae3b5f04b14a3d99db1141fb4880638a" yes will report when it happens next.

**Comment by jorgenschaefer** [comment] 2015-06-16 12:10
The log provided by the user showed repeated 352 and 315 numerics, which are apparently caused by ZNC or similar.

I'm unsure what the correct solution here would be. If a user sends a `/WHO` query, responses should go to the current buffer. Circe can't really distinguish WHO responses from user commands and ZNC. So Circe can't really "do the right thing" here. I'd call this a bug in ZNC.

There seems to be a solution for this bug, too:

> _If you connect to one ZNC user with multiple clients, you may see a lot of useless stuff like /who replies. This module fixes this by sending those replies only to the client who requested them and not to all clients."

http://wiki.znc.in/Route_replies

Does that solve the problem?

**Comment by jorgenschaefer** [comment] 2015-08-08 14:18
Any update on this?

**Comment by V155** [comment] 2015-08-08 19:05
IIRC You suggested to add those numerics to a list that gets filtered?
And in the meantime I also changed from weechat to znc

**Comment by jorgenschaefer** [comment] 2015-08-09 08:50
> IIRC You suggested to add those numerics to a list that gets filtered?

You can use the following:

```Lisp
(circe-set-display-handler "315" 'circe-display-ignore)
(circe-set-display-handler "352" 'circe-display-ignore)
```

The problem is that you won't see `/WHO` replies anymore, either. Not sure if that's a problem for you, that command is rarely useful.

Or you use the "route replies" module mentioned above.

**Comment by jorgenschaefer** [comment] 2016-05-12 13:22
Lacking further updates, I assume this problem is resolved by now :-) Do not hesitate to open a new issue if you have further problems, and enjoy Circe!

**Closed by jorgenschaefer** 2016-05-12 13:22 UTC
Labels: bug, More info needed
