### ISSUE TITLE
/part creates: Error running event nil handler circe-irc-legacy-bridge: (wrong-type-argument arrayp nil)

### ISSUE THREAD

**Issue by gour** [jorgenschaefer/circe#176] opened 2015-06-15 06:43 UTC
Hello,

when I part some (Freenode) chanel, I get the following:

```
Debugger entered--Lisp error: (wrong-type-argument arrayp nil)
  irc-channel-user(nil "gour")
  circe-lurker-p("gour")
  circe-display-PART("gour" "~gour" "unaffiliated/gour" "PART" ("#pcbsd-dev"))
  circe-server-display-message("gour" "~gour" "unaffiliated/gour" "PART" ("#pcbsd-dev"))
  circe-irc-legacy-bridge(#<process chat.freenode.net> "PART" "gour!~gour@unaffiliated/gour" "#pcbsd-dev")
  apply(circe-irc-legacy-bridge (#<process chat.freenode.net> "PART" "gour!~gour@unaffiliated/gour" "#pcbsd-dev"))
  irc-handler-run(#s(hash-table size 65 test equal rehash-size 1.5 rehash-threshold 0.8 data (nil (circe-irc-legacy-bridge) "conn.disconnected" (circe-irc-conn-disconnected irc-handle-registration--disconnected) "conn.connected" (irc-handle-registration--connected) "001" (irc-handle-registration--rpl-welcome irc-handle-state-tracking--rpl-welcome) "CAP" (irc-handle-registration--cap) "AUTHENTICATE" (irc-handle-registration--authenticate) "PING" (irc-handle-ping-pong--ping) "005" (irc-handle-isupport--005) "432" (irc-handle-initial-nick-acquisition--get-initial-nick) "433" (irc-handle-initial-nick-acquisition--get-initial-nick) "437" (irc-handle-initial-nick-acquisition--get-initial-nick) "PRIVMSG" (irc-handle-ctcp--privmsg irc-handle-state-tracking--PRIVMSG irc-handle-nickserv--NOTICE) "irc.ctcp" (irc-handle-ctcp--ctcp) "NOTICE" (irc-handle-ctcp--notice irc-handle-nickserv--NOTICE) "irc.ctcpreply" (irc-handle-ctcp--ctcpreply) "irc.ctcp.VERSION" (irc-handle-ctcp--ctcp-version) "irc.ctcp.CLIENTINFO" (irc-handle-ctcp--ctcp-clientinfo) "irc.ctcp.SOURCE" (irc-handle-ctcp--ctcp-source) "irc.ctcp.PING" (irc-handle-ctcp--ctcp-ping) "irc.ctcp.TIME" (irc-handle-ctcp--ctcp-time) "JOIN" (irc-handle-state-tracking--JOIN) "PART" (irc-handle-state-tracking--PART) "KICK" (irc-handle-state-tracking--KICK) "QUIT" (irc-handle-state-tracking--QUIT) "NICK" (irc-handle-state-tracking--NICK irc-handle-nickserv--NICK) "353" (irc-handle-state-tracking--rpl-namreply) "366" (irc-handle-state-tracking--rpl-endofnames) "TOPIC" (irc-handle-state-tracking--TOPIC) "331" (irc-handle-state-tracking--rpl-notopic) "332" (irc-handle-state-tracking--rpl-topic) "irc.registered" (irc-handle-nickserv--registered irc-handle-auto-join--registered) "396" (irc-handle-auto-join--rpl-hosthidden) "nickserv.regained" (irc-handle-auto-join--nickserv-regained) "nickserv.identified" (irc-handle-auto-join--nickserv-identified) ...)) nil #<process chat.freenode.net> "PART" "gour!~gour@unaffiliated/gour" "#pcbsd-dev")
  apply(irc-handler-run #s(hash-table size 65 test equal rehash-size 1.5 rehash-threshold 0.8 data (nil (circe-irc-legacy-bridge) "conn.disconnected" (circe-irc-conn-disconnected irc-handle-registration--disconnected) "conn.connected" (irc-handle-registration--connected) "001" (irc-handle-registration--rpl-welcome irc-handle-state-tracking--rpl-welcome) "CAP" (irc-handle-registration--cap) "AUTHENTICATE" (irc-handle-registration--authenticate) "PING" (irc-handle-ping-pong--ping) "005" (irc-handle-isupport--005) "432" (irc-handle-initial-nick-acquisition--get-initial-nick) "433" (irc-handle-initial-nick-acquisition--get-initial-nick) "437" (irc-handle-initial-nick-acquisition--get-initial-nick) "PRIVMSG" (irc-handle-ctcp--privmsg irc-handle-state-tracking--PRIVMSG irc-handle-nickserv--NOTICE) "irc.ctcp" (irc-handle-ctcp--ctcp) "NOTICE" (irc-handle-ctcp--notice irc-handle-nickserv--NOTICE) "irc.ctcpreply" (irc-handle-ctcp--ctcpreply) "irc.ctcp.VERSION" (irc-handle-ctcp--ctcp-version) "irc.ctcp.CLIENTINFO" (irc-handle-ctcp--ctcp-clientinfo) "irc.ctcp.SOURCE" (irc-handle-ctcp--ctcp-source) "irc.ctcp.PING" (irc-handle-ctcp--ctcp-ping) "irc.ctcp.TIME" (irc-handle-ctcp--ctcp-time) "JOIN" (irc-handle-state-tracking--JOIN) "PART" (irc-handle-state-tracking--PART) "KICK" (irc-handle-state-tracking--KICK) "QUIT" (irc-handle-state-tracking--QUIT) "NICK" (irc-handle-state-tracking--NICK irc-handle-nickserv--NICK) "353" (irc-handle-state-tracking--rpl-namreply) "366" (irc-handle-state-tracking--rpl-endofnames) "TOPIC" (irc-handle-state-tracking--TOPIC) "331" (irc-handle-state-tracking--rpl-notopic) "332" (irc-handle-state-tracking--rpl-topic) "irc.registered" (irc-handle-nickserv--registered irc-handle-auto-join--registered) "396" (irc-handle-auto-join--rpl-hosthidden) "nickserv.regained" (irc-handle-auto-join--nickserv-regained) "nickserv.identified" (irc-handle-auto-join--nickserv-identified) ...)) nil #<process chat.freenode.net> "PART" ("gour!~gour@unaffiliated/gour" "#pcbsd-dev"))
  irc-event-emit(#<process chat.freenode.net> "PART" "gour!~gour@unaffiliated/gour" "#pcbsd-dev")
  apply(irc-event-emit #<process chat.freenode.net> "PART" "gour!~gour@unaffiliated/gour" "#pcbsd-dev")
  irc--handle-line(#<process chat.freenode.net> ":gour!~gour@unaffiliated/gour PART #pcbsd-dev")
  irc--filter(#<process chat.freenode.net> ":gour!~gour@unaffiliated/gour PART #pcbsd-dev
\n")
```

**Comment by jorgenschaefer** [comment] 2015-06-15 07:00
Thank you for the report! This looks very similar to #171, both are caused by a nil as the first argument to `irc-channel-user`, though the error is different – possibly a different Emacs version? Anyhow, a bug that needs to be fixed.

**Comment by gour** [comment] 2015-06-15 07:53
GNU Emacs 24.5.1 (amd64-portbld-freebsd10.0, GTK+ Version 2.24.27) here (Free/PC-BSD)

**Comment by jorgenschaefer** [comment] 2015-06-16 15:33
This should be fixed in the latest git version – can you verify that?

**Comment by gour** [comment] 2015-06-17 05:25
It fixes the problem...although now I get:

```
irc-format: Wrong type argument: stringp, nil 
```
(no backtrace), after launching Circe, although it's probably not related.

**Comment by jorgenschaefer** [comment] 2015-06-17 07:08
The latest version shouldn't have such an error. Are you sure you did `M-x toggle-debug-on-error` (enabled) and you still did not get a backtrace?

**Comment by gour** [comment] 2015-06-17 07:33
Yes.

```
Debug on Error enabled globally
irc-format: Wrong type argument: stringp, nil
```

**Comment by jorgenschaefer** [comment] 2015-08-08 14:17
This is probably feeling a bit weird, but as I have no idea how this is possible … is this still happening?

**Comment by gour** [comment] 2015-08-08 14:52
I must admit, that I returned back to weechat...

**Comment by jorgenschaefer** [comment] 2015-08-08 14:54
That's perfectly fine. Enjoy the client, and sorry for not being more help here. :-)

Sadly, lacking reproduction I'll close this issue.

**Closed by jorgenschaefer** 2015-08-08 14:54 UTC
Labels: bug, More info needed
